// Mocks generated by Mockito 5.4.6 from annotations
// in shared_services/test/auth/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:shared_services/api/api_config.dart' as _i2;
import 'package:shared_services/api/base_api_client.dart' as _i4;
import 'package:shared_services/storage/token_storage.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiConfig_0 extends _i1.SmartFake implements _i2.ApiConfig {
  _FakeApiConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseApiClient extends _i1.Mock implements _i4.BaseApiClient {
  MockBaseApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeApiConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.ApiConfig);

  @override
  set tokenProvider(_i3.Future<String?> Function()? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #tokenProvider,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<T> get<T>(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, String>? queryParameters,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #headers: headers,
            #queryParameters: queryParameters,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [endpoint],
                  {
                    #headers: headers,
                    #queryParameters: queryParameters,
                    #fromJson: fromJson,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #get,
                [endpoint],
                {
                  #headers: headers,
                  #queryParameters: queryParameters,
                  #fromJson: fromJson,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> post<T>(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #headers: headers,
            #body: body,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #post,
                  [endpoint],
                  {
                    #headers: headers,
                    #body: body,
                    #fromJson: fromJson,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #post,
                [endpoint],
                {
                  #headers: headers,
                  #body: body,
                  #fromJson: fromJson,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> put<T>(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #headers: headers,
            #body: body,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #put,
                  [endpoint],
                  {
                    #headers: headers,
                    #body: body,
                    #fromJson: fromJson,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #put,
                [endpoint],
                {
                  #headers: headers,
                  #body: body,
                  #fromJson: fromJson,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> delete<T>(
    String? endpoint, {
    Map<String, String>? headers,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #headers: headers,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #delete,
                  [endpoint],
                  {
                    #headers: headers,
                    #fromJson: fromJson,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #delete,
                [endpoint],
                {
                  #headers: headers,
                  #fromJson: fromJson,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<void> deleteNoResponse(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNoResponse,
          [endpoint],
          {#headers: headers},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i6.TokenStorage {
  MockTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveTokens({
    required String? accessToken,
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveUserInfo({
    required String? userId,
    required String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserInfo,
          [],
          {
            #userId: userId,
            #email: email,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getEmail() => (super.noSuchMethod(
        Invocation.method(
          #getEmail,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> hasTokens() => (super.noSuchMethod(
        Invocation.method(
          #hasTokens,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
